# database for server runtime (relative to project root)
database.path=src/main/resources/database/vCampus.accdb

# socket config
socket.enabled=true
socket.serverPort=9090
socket.adminToken=changeme
